### ISSUE TITLE
ThingMagic/use_serialport/ 

### ISSUE THREAD

**Issue by romainrobotics** [paulvha/ThingMagic#1]
There doesn't seem to be a file here. Are you able to use MercuryApi connecting the reader to the UART of the Raspberry Pi?

I've tried using logic level shifters to protect the GPIO pins from the 5V of the Sparkfun simultaneous RFID tag reader, but I always get connection time-outs.

**Comment by paulvha** [comment]
I am out on vacation on the moment. Will respond next week..

Outlook voor Android downloaden<https://aka.ms/ghei36>

________________________________

**Comment by paulvha** [comment]
Just reading in more detail. The standard mercuri api works on a raspberry pi. Found some later version caused a compiler error and needed to make a number of changes in the source code.
Regards
Paul

Outlook voor Android downloaden<https://aka.ms/ghei36>

________________________________

**Comment by romainrobotics** [comment]
Thanks for looking into it. For now, I'm just having the Pi communicate with an Arduino via UART, then the Arduino controls the Sparkfun SRTR separately.
