### ISSUE TITLE
the example code, Example15_readallbanks , doesn't work well. 

### ISSUE THREAD

**Issue by minwinmin** [paulvha/ThingMagic#2]
I attempted to use [this library](https://github.com/paulvha/ThingMagic/blob/master/Arduino_lib_special/SparkFun_Simultaneous_RFID_Tag_Reader_Library_May2020.zip) on "SparkFun Simultaneous RFID Reader - M6E Nano".
And I tried to use the example code, "Example15_readallbanks". 
But it didn't work well.
What should I do?  

![image](https://user-images.githubusercontent.com/25277399/90456656-812d4c80-e134-11ea-99ed-25f3e76a8daf.png)

**Comment by minwinmin** [comment]
I'm sorry...
It was solved...
Old library was in conflict...
I deleted it, then it works well.

**Comment by fawadbutt** [comment]
Hi, 
@minwinmin where you find supported lib,  i use orginal sparkfun lib but some function is mission  like getTemp etc.
