### ISSUE TITLE
Sparkfun Artemis compatability?

### ISSUE THREAD

**Issue by dyones7** [paulvha/ThingMagic#6]
Hello paulvha,

I was looking for a solution to reading a RFID chip with user that extends past the usual 64 bytes and came across you library.

I am running on the Arduino platform but can't see to get you library to compile, for any Arduino.

Do you support the Arduino and if so can you tell me how to set it up so I can try your library.

Most appreciated,

dyones7

**Comment by paulvha** [comment]
Hi

This should compile on an Arduino MEGA2560 without any issues. On the Arduino UNO the small memory size might be a problem. What errors do you get so I can see if I can help.

Regards,
Paul

Verzonden vanuit Mail<https://go.microsoft.com/fwlink/?LinkId=550986> voor Windows 10

Van: ***@***.***>
Verzonden: maandag 26 april 2021 03:54
Aan: ***@***.***>
CC: ***@***.***>
Onderwerp: [paulvha/ThingMagic] Sparkfun Artemis compatability? (#6)


Hello paulvha,

I was looking for a solution to reading a RFID chip with user that extends past the usual 64 bytes and came across you library.

I am running on the Arduino platform but can't see to get you library to compile, for any Arduino.

Do you support the Arduino and if so can you tell me how to set it up so I can try your library.

Most appreciated,

dyones7

**Comment by dyones7** [comment]
Hello paulvha,

I have attached my modified code and the error for the mega and the artemins. Note I am using Serial1 for both.

I don’t have a lot of experience with the inner working of Arduino. I  brought in your library as a zip file. Since I already have the SparkFun reader library installed, I include you header file by giving it the entire path. Don’t know fi this is a good thing to do or not.

Thanks for you help,
Dale

**Comment by paulvha** [comment]
it can not find the header-file ( .h). remove the original sparkfun library and just use mine. All what the original library had is still in my library. Then use the examples as they are.

regards,
Paul

**Comment by dyones7** [comment]
Ok thanks. I actually had 3 different libs, removed the two from Sparkfun and not it seems to compile fine.  Like I said just digging into Arduino fun.

Thanks again,
Dale

From: paulvha ***@***.***>
Sent: Monday, April 26, 2021 10:02 AMTo: paulvha/ThingMagic ***@***.***>

Cc: Dale Yones ***@***.***>; Author ***@***.***>
Subject: Re: [paulvha/ThingMagic] Sparkfun Artemis compatability? (#6)


it can not find the header-file ( .h). remove the original sparkfun library and just use mine. All what the original library had is still in my library. Then use the examples as they are.

regards,
Paul
